### ISSUE TITLE
Implement privacy provider class

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#12]
At some point would be good to implement the privacy provider class for proper GDPR support - you will need to implement the external link stuff to say that you pass the users fullname externally:
more info:
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

Because you have a single branch in github which supports Moodle 3.3 and higher you will also need to use the polyfill as your initial template which is here:
https://docs.moodle.org/dev/Privacy_API#Difference_between_Moodle_3.3_and_more_recent_versions

this won't block approval in the plugins db, just something that would be worth adding at some point.

**Comment by deedey** [comment]
I will keep this issue open so as not to forget it and implement it as soon as I understand and analyze everything.
I know it's very important.
This is why the LRS Annulab allows the user to retrieve all personal tracking data at any time.
It also allows the administrator to recover all the JSON relating to his Moodle in order to change the LRS if necessary.
![2018-05-25_095420](https://user-images.githubusercontent.com/5656024/40533056-c2195b28-6001-11e8-8ed6-825101e0a354.jpg)

**Comment by deedey** [comment]
Hi Dan,
I've added privacy provider class and strings ad-hoc as you had previously recommended to finalize this block.
What do you think about?
Regards

**Comment by danmarsden** [comment]
awesome - nice work!!!!
... I'm not sure any software can be "finalized" :-)  - there will always be improvements/bugs/other stuff to add/versions to add support for etc etc..

My work as Plugin Guardian is done now that your plugin has been approved in the plugins db - I'll leave it now for the end-users who install your plugin to give you further feedback/feature suggestions etc.

Thanks for sharing! :-)
