### ISSUE TITLE
incorrect use of dml functions.

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#3]
variables should never be added to inline sql - you should be using paramters - eg this line:
https://github.com/deedey/moodle_annulabLRS/blob/master/block_annulab_lrs.php#L47
$IsTeacher = $DB->count_records_select('role_assignments','userid = '.$USER->id.' AND (roleid = 1 OR roleid = 3)');

should be more like this:
  $IsTeacher = $DB->count_records_select('role_assignments','userid = ? AND (roleid = ? OR roleid = ?)', array($USER->id, 1, 3);

but... the hard-coded role ids are wrong too..  You cannot assume that those roles exist or that the ids are the ones you have included there.

You should really replace that $isteacher line with something that relates to a capability usually assigned to teachers within the course - or you could define a new capability in your block that is given to the teacher role by default and check that capability.

**Comment by deedey** [comment]
The correction you offer is excellent. I'm going to implement it. Thank you.
By cons I keep this option.
I chose it to test if the User is at least manager or teacher, which will give him an additional right to manage his own courses in the Annulab LRS.
Annulab LRS is responsible for giving it rights based on data collected in JSON strings.
It is then enough for him to be at least once in a course in role 1 or 3 to obtain the rights because it allows him to directly display this block in his dashboard and in all other contexts.
Other roles can only display it in the dashboard.
These rights do not imply an interaction with Moodle but only with LRS Annulab
Do you agree that, Dan?

**Comment by danmarsden** [comment]
I would probably use get_user_capability_course for this.
something like 
$isteacher = get_user_capability_course('block/annulab_lrs:addinstance', $USER, true, '', '', 1);

I'd pass "1" as the final parameter there because you don't need a list of courses - you just need to know if the user is a teacher in any course and just returning a single entry will make that function a lot faster for users who are teachers in a lot of courses.

you might even want to use that method when the user has added it to their dashboard and then use a simple has capability when the block is on a course page like this:

    $isteacher = has_capability('block/annulab_lrs:addinstance', $coursecontext);

The main point is that you should be checking a capability here - not looking for a "role"

**Comment by deedey** [comment]
Hi Dan,
It is a good idea.
I've replaced this sequence by:
           $IsTeacher = get_user_capability_course('block/annulab_lrs:addinstance', null, true, '', '', 1);
           $flag = (empty($IsTeacher)) ? 0 : 1 ;
and it work fine.
Thank you
